Bug: AUC start 0 (which also needs Feature: C0 imputation)
pharmaverse/aNCA pull request #138
Opened 2024-11-27 14:27 UTC by Gero1999

## Issue
Closes #2 #60

## Description
After running NCA, AUC calculations always consider the discrete start (start at where first concentration sample was collected). This can indeed alter slightly the real values of the AUC. This is a consequence of 2 problems:

1) Doses times are being considered at the first measure, instead of at the real dose time
2) No imputed measure at dose time is consdiered

Change description.

## Definition of Done
C0 imputation option for the user specified in Setup > Data Selection

## How to test
- [x] At "NCA">"NCA Results", when C0 is imputed it is expected that start=AFRLT-ARRLT (being AFRLT-ARRLT= 0 in DOSNO=1)
- [x] At "NCA">"NCA Results", when C0 is not imputed it is expected that start={time of 1st observation} 
- [ ] AUC values  (auclast, aucinf...) from start=AFRLT-ARRLT are calculated when C0 is imputed
- [ ] All variables that should only be based on observed data (cmax, tmax...) are not considering C0 imputations
- [ ] Test that PKNCA also deals well with predoses as duplicates

## Contributor checklist
- [ ] Code passes lintr checks
- [ ] Code passes all unit tests
- [ ] New logic covered by unit tests
- [ ] New logic is documented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

2024-12-05 11:00 UTC, js3110 requested changes
Nice work! Some requests:

Fixes:
- [ ] App crashes if AUC rule sets are selected
- [ ] Slope selector not working- i tested an exclusion and the app crashed. Haven't tried selections.
- [ ] Data table in Data selection tab is not sorted- needs to be sorted by USUBJID for better visualisation.

Enhancements:

- It would be good if the user can see an updated data table after the imputations, so they know what the data being used looks like. If this is too complex then maybe you can add an explanation of what the imputation is doing. But it would be good if they can see what data is being created.
- Some clarification/relabelling is required in terms of what the imputation does. 'C0 missing' is not always accurate, for example if the predose value is present in the data set but ATime is <0, it gets excluded, but its not technically missing. Some more clarification on this would be good for the user so they know that imputation is also for predose samples.
- Predose samples/ duplicates are not being included. Need to figure out a way to ensure they are- by creating duplicates manually or making sure PKNCA includes them.

2024-12-12 14:56 UTC, m-kolomanski requested changes
Hey,

Are the diffs displayed by github accurate? Seems like a lengthy change, are there any artifacts/errors that happened due to merge (it did happen to me on occasions)? If the diffs are inaccurate, please point out the actual changes and disregard the below.

I do not have the time to do a detailed review (it is quite a lengthy change), but after a quick look there is some general things I want to point out:

1. Please do not any files that solely generate UI to the `/R` folder - this is a folder for our logic. File `partial_auc_input` belongs in the `inst/shiny` folder, either in `/modules` (if there is any server logic attached, here it isnt, but might be added) or folder like `functions`. We can also create a new folder for UI elements, called `ui` or `elements` or `widgets` or whatever you find suitable.
2. If you are creating new files or adding new functions in the `/R` folder, please make sure that this logic is testable and do take some effort to write at least basic unit tests. Adding tests back to existing logic is tough and time consuming, so we should at least make sure that our testing suite keeps up with any new features or major changes to the old ones.
3.

2025-01-02 08:29 UTC, Gero1999 commented
> Hey,
> 
> Are the diffs displayed by github accurate? Seems like a lengthy change, are there any artifacts/errors that happened due to merge (it did happen to me on occasions)? If the diffs are inaccurate, please point out the actual changes and disregard the below.
> 
> I do not have the time to do a detailed review (it is quite a lengthy change), but after a quick look there is some general things I want to point out:
> 
> 1. Please do not any files that solely generate UI to the `/R` folder - this is a folder for our logic. File `partial_auc_input` belongs in the `inst/shiny` folder, either in `/modules` (if there is any server logic attached, here it isnt, but might be added) or folder like `functions`. We can also create a new folder for UI elements, called `ui` or `elements` or `widgets` or whatever you find suitable.
> 2. If you are creating new files or adding new functions in the `/R` folder, please make sure that this logic is testable and do take some effort to write at least basic unit tests. Adding tests back to existing logic is tough and time consuming, so we should at least make sure that our testing suite keeps up with any new features or major changes to the old ones.

Hello and happy new year @m-kolomanski !

You are right, this is a very lengthy change but I re checked and everything was intentional. Most of them are new created manuals for each function. As requested I also:

1. Deleted the extra UI function from `\R`
2. Added tests for all functions called in ``format_data,R`, `create_start_impute` and `PKNCA_impute_method_additions`

Don't hesitate to let me know if there is anything else I can do or if there are other concerns that I can address! I also asked @js3110 for re-review to make sure all looks as expected.

2025-01-02 08:32 UTC, js3110 approved these changes
LGTM

Need to create a new issue for the auc calculation to avoid using cmax automatically.

2025-01-02 15:35 UTC, m-kolomanski requested changes
Hey, happy new year to you too and thank you for all the hard work!

I have to request some changes and have some suggestions/nitpicks to consider. I know that some of my comments refer to lines that were not changed in this PR, but since we are working on those functions I think it would be beneficial to go back and improve the code, even if it is not directly related to the changes.

2025-01-02 15:35 UTC, m-kolomanski commented on tests/testthat/test-format_data.R
> +  )
issue: In this case, if `df_conc` was somehow wrong, we would expect an error from `PKNCAconc` function, so I would wrap that in `expect_no_error` to know exactly if a) an error occured or b) `PKNCAconc` returned something strange.
```suggestion
  expect_no_error({
    expect_s3_class(
      PKNCAconc(
        df_conc,
        formula = AVAL ~ TIME | STUDYID + PCSPEC + DRUG + USUBJID / ANALYTE,
        exclude_half.life = "exclude_half.life",
        time.nominal = "NFRLT"
      ),
      "PKNCAconc"
    )
  })
```

2025-01-02 15:35 UTC, m-kolomanski commented on tests/testthat/test-format_data.R
> +  expect_s3_class(
issue: As above, I would wrap that in `expect_no_error`.

2025-01-02 15:35 UTC, m-kolomanski commented on tests/testthat/test-format_data.R
> +  expect_s3_class(
issue: As above, I would wrap that in `expect_no_error`.

2025-01-02 15:35 UTC, m-kolomanski commented on tests/testthat/test-format_data.R
> +  expect_s3_class(
issue: As above, I would wrap that in `expect_no_error`.

2025-01-02 15:35 UTC, m-kolomanski commented on R/format_data.R
> +  data <- ADNCA %>%
issue: variable assignment not needed, can just return the pipe result
```suggestion
  ADNCA %>%
```

2025-01-03 12:56 UTC, Gero1999 commented on R/PKNCA_impute_method_additions.R
> +  mask_start <- time %in% start
I think you are right. It is an unnecessary prevention of NAs in case `time` contains them, but it should not at this point

2025-01-03 12:58 UTC, Gero1999 commented on R/PKNCA_impute_method_additions.R
> +  ret <- data.frame(conc = conc, time = time)
I asked Bill because I actually followed his syntax from the other parallel functions. Apparently is from the word `return` (of the function). But I will change it to something more intuitive now

2025-01-03 14:03 UTC, Gero1999 commented on R/PKNCA_impute_method_additions.R
> +  ret <- data.frame(conc = conc, time = time)
I put `d_conc_time`, hope that makes more sense!

2025-01-13 14:24 UTC, Gero1999 commented on R/create_start_impute.R
> +create_start_impute <- function(mydata) {
I agree with this but I would prefer to change all `mydata` calls together at once to something we set. Maybe in an independent issue for renaming variables would be the best

2025-01-15 08:24 UTC, Gero1999 commented
Thanks for your reviews and feedback, I hope that now all looks fine! @js3110 @m-kolomanski

2025-01-15 13:14 UTC, m-kolomanski requested changes
Hey, looks much better, thank you for all the hard work! I still do have some feedback, most of it regards style and consistency rather thank quality of the code, but also there seems like some of my comments from the previous review were not addressed?

2025-01-15 14:55 UTC, js3110 commented
@Gero1999 it looks good and thank you for all the hard work on this! Unfortunately I have noticed a couple of things:

1. In the data selection, after you select analyte and dose number, the table shown does not represent the selections, as I can still see all the dose numbers. We want this table for the user to see exactly the data that will be used for NCA, so either we need to filter the dose number here, or move the dose number selectInput. I will let you decide.
2. For the dummy data, Doseno >3 does not work and the app crashes. I get the following error: Error in if: argument is of length zero. I double checked and I do not get this issue in main, so it is related to something in this branch. Also, for DOSNO = 2, USUBJID 11102 has empty cells for lambda z calculation, but no explanation why and because of this the slope selection crashes. This could be created as a separate bug issue to fix later or you can see if its something to fix now.

Let me know if you have any questions or want any support :)

2025-01-17 06:44 UTC, m-kolomanski approved these changes
From my side, looks good! Thank you for all the hard work, this is a lengthy change, sure it was not easy!

I am approving, but before merge, please remove the `inst/WORDLIST.txt` file, as it is redundant - the spelllcheck only uses `WORDLIST` file.

2025-01-17 06:44 UTC, m-kolomanski commented on R/PKNCA_impute_method_additions.R
> +    all_times <- time[time >= start  &  time <= end]
nitpick, style: 
```suggestion
    all_concs <- conc[time >= start & time <= end]
    all_times <- time[time >= start & time <= end]
```

2025-01-17 06:44 UTC, m-kolomanski commented on R/create_start_impute.R
> +        is.ivbolus & is.analyte.drug ~ "start_c1"
Nice, looks clean, thank you for additional comments with explanations!

2025-01-17 06:44 UTC, m-kolomanski commented on inst/WORDLIST.txt
issue(non-blocking): Please remove this file, it is redundant.

2025-01-17 07:51 UTC, js3110 approved these changes
LGTM !!

2025-01-17 07:57 UTC, merged