Enhancement: Units edition results
pharmaverse/aNCA pull request #146
Opened 2024-12-17 15:48 UTC by Gero1999

## Issue
Users would like to be able to choose the units in which the results parameters are displayed.
Closes #113 

## Description
Sometimes user might be interested in changing the standard format of units provided by the app. In one that this may happen frequently is for example clearance (cl.obs), where current units always make very small values (~0) that can confuse when the rounding is used in the summary statistics.

## Definition of Done
- [ ]  Allow user to customize in results the units of measure for each parameter
- [ ]  Scale appropriately parameter values based on new unit measures imputed

## How to test

How to test features not covered by unit tests.

## Contributor checklist
- [ ] System to change units in parameters works well before NCA
- [ ] System to change units in parameters works well after NCA
- [ ] Outputs post NCA still work fine and adapt well to new units (i.e, boxplots)

- [ ] Code passes lintr checks
- [ ] Code passes all unit tests
- [ ] New logic covered by unit tests
- [ ] New logic is documented

## Notes to reviewer

Anything that the reviewer should know before tacking the pull request?

2025-01-02 16:26 UTC, Gero1999 commented
Hello team @m-kolomanski @Gotfrid @js3110 ! 

I have a small technical problem with this `units` package. This is a package that I used for the function `transform_unit` that automatically calculates conversions. This package is also used in PKNCA and @billdenney has also participated in its development. 

When the package is installed through non-Windows OS, the installation through CRAN with `install.packages()` won't work unless  a terminal command is run before to install the udunits2 object, as indicated in their [README](https://github.com/r-quantities/units) . The problem is that the testing on the remote GitHub-workflow might require this, as it is a Linux system. 

There are many potential solutions to this, as the only affected things are the `transform_unit` function and its testthat testing. However I am not sure what is the best approach to solve it and I would like your input if possible. Here are my current ideas:

 1) Add the package `units` to "Suggests" in the namespace, and only run `transform_unit` when possible with `if (!requireNamespace("units", , quietly = TRUE)` (in other cases return NA, which does not conflict with the App, as the user will be asked to manually populate the conversions).
 
 2) Customize somehow the installation for each OS. I know that with R we can request the `Sys.info()` to obtain all info we need (`sysname` + perhaps `version`) to know what action to take before doing the `install.packages`. However this procedure concerns me, as I am not sure if we require additional permits from the user to do this installation method. 
 
 3) Do a function that is independent from the `units` package that is only intended for the physical units we use (concentration, time, volume, mass). I indeed did something of this in the past using regex, I would just need to refine it and create the tests. 
 
 Let me know what you think of them or if you could come up with a better solution and I will try to implement it!

2025-01-02 16:55 UTC, m-kolomanski commented
Hi @Gero1999,

use whatever dependencies you need to use - there is no need to re-invent the wheel if ready solutions are available, and we are not the first to deal with system dependencies, so do not worry :)

In terms of installing the package itself, if installing a dependency (in that case `units`) fails due to missing system packages, the user is prompted to install those and this is alright - something that I deal with frequently as Ubuntu user. We only need to make sure that the package is present in the DESCRIPTION file. I do not think there are any other concerns, @Gotfrid?

In terms of github actions / workflows, we can install the dependency on the machine that runs the checks, I will get on that.

2025-01-02 16:58 UTC, billdenney commented
I agree with @m-kolomanski, adding the dependency is the best path. Writing your own unit handling will likely be error-prone. (I've done it a few times in the past, and it always has lots of bugs the first time around.) The units package has the side-benefit that all standard unit conversions should be handled for you.

2025-01-06 12:01 UTC, Gotfrid commented
Agreed with everything mentioned above regarding the `units` package. It is not uncommon to require system dependencies installed in the environment (think `sf` package, or any DBMS package).
Comment from my end: once `units` is added to the dependencies, we can recommend installation via `pak` - because it handles system requirements as well (99% of the time).

2025-01-07 16:20 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
> +  })
suggestion: This also could be wrapped into single `reactive()` expression and returned directly. You can use `bindEvent` to bind a reactive expression to a single specific event, instead of recalculating it every time some dependency change (it is basically like wrapping it in `isolate()`.

```R
reactive({
  # code for pepraring the results
  removeModal()
  res_nca
})
```

2025-01-07 16:25 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
issue: There are a lot of side-effect in this module and they seem to not be consistent. You are modifying `mydata()` object directly in this module, but instead of also modifying `res_nca()` directly you return it as a reactive, and then assign the value in `anca.R` file (Line 37). There is nothing inherently wrong with mutating the state of the object directly, but it gets confusing as the complexity grows and might be hard to debug later on. Please make sure all side-effects of the module are desired and documented.

2025-01-07 16:29 UTC, m-kolomanski commented on inst/shiny/tabs/nca.R
> +observeEvent(res_nca2(), res_nca(res_nca2()))
question: So if I understand that correctly, we are using `units_table_preNCA` module to modify only `mydata` object, but use `units_table_postNCA` to modify both `mydata` and `res_nca`? This is a bit confusing and relates to my previous comment about side-effects. Seems like a single instance of the module should be able to handle both cases (and just return NULL if `res_nca` is not available).

2025-01-07 16:31 UTC, m-kolomanski commented on inst/shiny/tabs/nca.R
> +res_nca <- reactiveVal(NULL)
issue: `res_nca` is referenced on line 307, but only defined on line 387. This does not cause any technical problems because of the even structure of the program, but is bad practice nevertheless - this should be higher. Considering the importance of that data, I would consider putting this definition on top of the module.

2025-01-08 12:21 UTC, Gero1999 commented on R/transform_unit.R
> +        NA
The section in the app where the function is applied will notify the users if any NA is set as a conversion factor. It will ask them to either introduce themselves the appropriate conversion factor or to change the target_unit to one that is accepted by `units` library

2025-01-08 13:10 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
> +            )
After looking at it again, the glue syntax might cause problems with brackets in the code, maybe simply pasting is a better solution:
```R
paste0("
  function() {
    var paramsToCalculate = ", parameters_array_string, ";
    // ...
")
```

2025-01-17 11:09 UTC, Gero1999 commented
I ended up merging instead of rebasing because in practice seemed less messy to me (I needed way too many commtits when rebasing). Hope is fine! Regarding some aspects of the module simplicity @m-kolomanski, I tried to document better the changes that occur:

1) I did not manage to make them explicit, although now they are implicit for both objects
2) I did not maange to only make 1 server call, because the UI has two input definitions and seems that I cannot repeat the same one two times!

But please let me know any concern with these solutions

2025-01-17 11:31 UTC, m-kolomanski requested changes
Hey, it looks quite nice, but there are some minor issues to iron out.

The data flow is still a bit confusing, but I think we should fix that in the scope #144 , when modularizing the whole NCA tab.

2025-01-17 11:31 UTC, m-kolomanski commented on R/get_conversion_factor.R
> +#' @return A numeric value for the conversion factor from the initial to the target unit,
nitpick: 
```suggestion
#' @returns A numeric value for the conversion factor from the initial to the target unit,
```

2025-01-17 11:31 UTC, m-kolomanski commented on tests/testthat/test-transform_unit.R
issue: Please utilize `describe` and `it` in the testing suite

2025-01-17 11:31 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
> +          tags$button(
issue: this button does not seem to do anything.

2025-01-17 11:31 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
> +units_table_server <- function(id, mydata, res_nca = reactive(NULL), params_to_calculate) {
issue:
```suggestion
units_table_server <- function(id, mydata, res_nca = reactiveVal(NULL), params_to_calculate) {
```
as the module expects `reactiveVal` as opposed to `reactive`

2025-01-17 11:31 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
issue, style: Please be consistent with namespacing the function calls, there is a mix.

2025-01-17 13:52 UTC, m-kolomanski approved these changes
Hey, to me, the code looks good, thank you!

Since this PR touches the `nca.R` file directly, and we wish to rework it ASAP, there are some minor issues / suggestions that we should create a separate issue for and address within a new PR:

- Bug: the application crashes when a text value is provided as conversion factor;
- Suggestion: If conversion factor returns NA, might be worth displaying something else in the table, as opposed to an empty cell (like **Error* or something, to explicitly inform user that there is something wrong).
- Suggestion: Disable the ability to select rows in unit table, as it does not provide any functionality.

2025-01-20 15:02 UTC, js3110 commented
> Hi @Gero1999 It looks really good! I love the layout especially.
> 
> However I have noticed that the nca results are missing a lot of parameters (such as CL clearance) , which is important as this parameter is the main reason we are trying to implement unit changes (for pre clinical)
> 
> I have had a check and the parameters are also missing in main, but not in our rsconnect version so it must have slipped through in the #109 merge. if you can fix it in this issue then great, and if not then lets make a separate issue for this!

Looks to me as if this is coming from the interval creation, as if you look at mydata() it is set as FALSE for most of the parameters except for the ones included in the format_pkncadata_intervals function. We want all the parameters to be available, or the user should be able to choose. Currently neither are possible.

2025-01-20 16:24 UTC, js3110 commented
I've created issue #168 as it is separate from this issue.

2025-01-20 16:24 UTC, js3110 approved these changes
LGTM

2025-01-21 12:33 UTC, Gero1999 commented
I implemented your requested changes @m-kolomanski

- Bug fixed -> conversion factor when given a text won't crush and gives a notification of the expected format
- Suggestion -> If conversion factor returns NA, an additional notification is sent to the user at the moment of the action
- Suggestion -> Instead of row selection they will have single cell selection. That way they have a better sense that the table is interactable and how it works!

As mentioned @js3110  I will use a different branch to make the input for NCA parameters. As soon as we merge this one to main I will create it and start working on it.

2025-01-21 13:18 UTC, js3110 commented
@Gero1999  LGTM! I just added cl.obs into the params as a temporary solution, so that the DPLs can use it for testing before #168 is finished.

2025-01-21 13:18 UTC, js3110 approved these changes

2025-01-21 14:22 UTC, Gero1999 commented
Hey @js3110 I added  `cl.obs`. Your commit did not work because it was just for the default function arguments

2025-01-23 07:27 UTC, m-kolomanski approved these changes
Hey, looks good, thank you for implementing the suggestions!

I am approving the PR, but leaving two minor, non-blocking nitpicks for consideration.

2025-01-23 07:27 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
> +      if (names(modal_units_table)[info$col + 1] == "Conversion Factor" && !is.numeric(info$value)) {
nitpick: might be work assigning `info$col + 1` to a variable, since it is repeated a bunch and then using that throughout.

2025-01-23 07:27 UTC, m-kolomanski commented on inst/shiny/modules/units_table.R
> +            duration = 5
nitpick: I would consider extending the duration and / or instead adding a close button, it might be a bit hard to read the whole error in 5 seconds.

2025-01-23 08:40 UTC, merged